In [2]:
import numpy as np
print(np.__version__)

1.26.4


In [3]:
arr = np.arange(0,10,1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr = np.full(shape=(3,3), fill_value=True, dtype= bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[(arr%2)!= 0]

array([1, 3, 5, 7, 9])

In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[(arr%2)!= 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr%2 != 0,-1,arr)
print(out)
arr


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr = np.arange(10)
arr.reshape((2,-1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a, b),axis=0)
# np.vstack((a, b))
# np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a, b), axis=1)
np.hstack((a, b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [11]:
a = np.array([1,2,3])
a*3

array([3, 6, 9])