# Práctica Clase 3

## Numpy

In [1]:
import numpy as np

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

A partir de una lista podemos crear un arreglo de numpy

In [2]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


In [30]:
'''En un arreglo como en una lista se pueden hacer las mismas operaciones exploratorias,
como imprimir un elemnto específico, hacer un slicing, iterar en sus elementos'''
print(lista[1])
print(arreglo[1])

1
1


In [32]:
print(lista[1:3])
print(arreglo[1:3])

[1, 2]
[1 2]


In [33]:
for i in lista:
    print('elemnto de lista', i)

for i in arreglo:
    print('elemento de arreglo', i)

elemnto de lista 0
elemnto de lista 1
elemnto de lista 2
elemnto de lista 3
elemnto de lista 4
elemnto de lista 5
elemento de arreglo 0
elemento de arreglo 1
elemento de arreglo 2
elemento de arreglo 3
elemento de arreglo 4
elemento de arreglo 5


Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [38]:
arreglo = np.arange(8)
print(arreglo)

[0 1 2 3 4 5 6 7]


Algunas cosas que se pueden hacer con arreglos pero no con las listas:

1. Sumarle un mismo elemento

In [35]:
lista + 1

TypeError: can only concatenate list (not "int") to list

In [40]:
arreglo = arreglo + 1

In [41]:
arreglo

array([1, 2, 3, 4, 5, 6, 7, 8])

2. Elevar al cuadrado todos los elementos

In [42]:
lista**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [43]:
arreglo**2

array([ 1,  4,  9, 16, 25, 36, 49, 64])

3. Sumar todos los elementos

In [44]:
print(arreglo.sum())
print(lista.sum())

36


AttributeError: 'list' object has no attribute 'sum'

In [45]:
n = 0
for e in lista:
    n = n + e
print(n)

15


In [46]:
arreglo.shape

(8,)

In [ ]:
'''En los arreglos se pueden realizar operaciones aritmeticas, de manera similar al trabajo con matrices.
Mientras en las listas no es posible o al menos no es tan simple'''

In [3]:
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (3, 6) 



In [4]:
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]] . Shape = (1, 6) 



In [5]:
# arreglo = np.array([[1,2,3,4,5,6]]).T #notar los corchetes extras
arreglo = arreglo.T
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [6]:
#¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?

print('Arreglo de (n,)')
arreglo = np.array([1,2,3,4,5,6])
print(arreglo,'. Shape =', arreglo.shape, "\n") # "\n" imprime un salto de linea

print('Arreglo de (2,n)')
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

print('Arreglo de (n,1)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo.T,'. Shape =', arreglo.T.shape, "\n")   #notar .T, que significa transpuesto


Arreglo de (n,)
[1 2 3 4 5 6] . Shape = (6,) 

Arreglo de (2,n)
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (2, 6) 

Arreglo de (n,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [ ]:
'''El arreglo de forma (n,) corresponde a un array de forma de vector
    El arreglo de forma (n,1) y (1, n) corresponden a array de forma matricial'''

In [21]:
### EXTRA 1###
#Trasponer no es la unica forma de crear un arreglo de forma (n,1)'''
arreglo = np.array([[1],[2],[3],[4],[5],[6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape)   #notar .T, que significa transpuesto

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1)


In [26]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a1.shape
print(a1)

[[1 2 3 4]
 [5 6 7 8]]


In [27]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2.shape
print(a2)

[[1 2 3 4]
 [5 6 7 8]]


In [25]:
a3 = a1 * a2
print(a3)
a3.shape

[[ 1  4  9 16]
 [25 36 49 64]]


(2, 4)

In [46]:
a3

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [5]:
arr2 = np.arange(start=0, stop=10, step=1)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
arr2b = np.linspace(0, 9, 100)
print(arr2b)
arr2b.shape

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.
 1.09090909 1.18181818 1.27272727 1.36363636 1.45454545 1.54545455
 1.63636364 1.72727273 1.81818182 1.90909091 2.         2.09090909
 2.18181818 2.27272727 2.36363636 2.45454545 2.54545455 2.63636364
 2.72727273 2.81818182 2.90909091 3.         3.09090909 3.18181818
 3.27272727 3.36363636 3.45454545 3.54545455 3.63636364 3.72727273
 3.81818182 3.90909091 4.         4.09090909 4.18181818 4.27272727
 4.36363636 4.45454545 4.54545455 4.63636364 4.72727273 4.81818182
 4.90909091 5.         5.09090909 5.18181818 5.27272727 5.36363636
 5.45454545 5.54545455 5.63636364 5.72727273 5.81818182 5.90909091
 6.         6.09090909 6.18181818 6.27272727 6.36363636 6.45454545
 6.54545455 6.63636364 6.72727273 6.81818182 6.90909091 7.
 7.09090909 7.18181818 7.27272727 7.36363636 7.45454545 7.54545455
 7.63636364 7.72727273 7.81818182 7.90909091 8.         8.09090909
 8.18181818

(100,)

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [12]:
arr3 = np.arange(start=10, stop=101, step=1, dtype=int)
arr3 = arr3.reshape(7,-1)
print(arr3)
mask3 = ((arr3%3) == 0)
# print(mask3)
arr3[mask3]

[[ 10  11  12  13  14  15  16  17  18  19  20  21  22]
 [ 23  24  25  26  27  28  29  30  31  32  33  34  35]
 [ 36  37  38  39  40  41  42  43  44  45  46  47  48]
 [ 49  50  51  52  53  54  55  56  57  58  59  60  61]
 [ 62  63  64  65  66  67  68  69  70  71  72  73  74]
 [ 75  76  77  78  79  80  81  82  83  84  85  86  87]
 [ 88  89  90  91  92  93  94  95  96  97  98  99 100]]


array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60,
       63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [13]:
arr4 = np.zeros(shape=(5,10))
# arr4[1] = [1]
# arr4[3] = [1]
# arr4[:,2] = [2]
# arr4[:,7] = [2]
print(arr4)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
arr4[[1,3],:] = 1
arr4[:,[2,7]] = 2
print(arr4)

[[0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]]


**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html

In [28]:
a = np.random.random((4,2,3)) * 100 + 100
a

array([[[151.86906599, 145.24026526, 197.94665457],
        [174.59848711, 128.70891345, 115.16218574]],

       [[151.40105779, 181.63867277, 139.3380176 ],
        [110.87141002, 182.53622573, 196.49476071]],

       [[148.75481098, 176.78189129, 179.37437612],
        [192.20963717, 117.33184639, 188.19295015]],

       [[133.39895043, 159.6914238 , 197.27137405],
        [180.29691016, 182.39143422, 158.45491679]]])

In [29]:
a = np.random.random((4,4))

In [30]:
a

array([[0.9984312 , 0.39844134, 0.53468389, 0.51728787],
       [0.75420189, 0.40358449, 0.45423302, 0.44637399],
       [0.87298307, 0.13309006, 0.01011759, 0.87670464],
       [0.80213976, 0.26606147, 0.03107018, 0.5029592 ]])

In [37]:
a = np.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]], dtype=np.int16)

In [38]:
a

array([[ 10, 200,  30,  45,   5,  50],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]], dtype=int16)

In [39]:
a.sum()

775

In [40]:
a.std()

39.15724620750999

In [41]:
a.sort(axis=1)

In [42]:
a

array([[  5,  10,  30,  45,  50, 200],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50]], dtype=int16)

In [43]:
a.sort(axis=0)
a

array([[  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  5,  10,  30,  45,  50, 200]], dtype=int16)

In [44]:
a[1:3,0:3]

array([[ 0,  5, 20],
       [ 0,  5, 20]], dtype=int16)

In [45]:
l =   [[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]]

In [48]:
a = np.array([l])

In [49]:
a.shape

(1, 4, 6)

In [50]:
a.reshape(24)

array([ 10, 200,  30,  45,   5, 100,   5,  20,  30,  40,  50,   0,   5,
        20,  30,  40,  50,   0,   5,  20,  30,  40,  50,   0])

In [51]:
a = np.matrix([[1,2,3,4,5,6]]) 
print(a) 

[[1 2 3 4 5 6]]


In [58]:
b = np.matrix([[1],[2],[3],[4],[5],[6]]) 
print(b) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [59]:
c = a * b 
print(c) 

[[91]]


In [60]:
d = b * a 
print(d)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


In [61]:
warr = np.full(shape=(4,2,3), fill_value=3)
print(arr.shape)
print(arr)

(4, 2, 3)
[[[3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]]]


In [5]:
arr = np.random.rand(4,2,3)
print(arr)

[[[0.26367679 0.86770292 0.40893379]
  [0.30888886 0.62312887 0.69796954]]

 [[0.76629389 0.90352366 0.10390615]
  [0.47314156 0.39063013 0.50342022]]

 [[0.33396585 0.18512226 0.32273844]
  [0.52769248 0.92242716 0.37474039]]

 [[0.83824466 0.02297545 0.98696392]
  [0.29557182 0.75075554 0.27057191]]]


In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[1:4])

[2 3 4]
